[package]
name = "rust-training"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[dependencies]
rand = "0.8.5"
libc = "0.2.168"
async-channel = "2.3.1"
tokio = { version = "1.43.0", features = ["full"] }